// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAcWnMnYYMNzRsPrOCr-2lMXJGyrDkJ2AY",
      authDomain: "dash-cdb16.firebaseapp.com",
      projectId: "dash-cdb16",
      storageBucket: "dash-cdb16.appspot.com",
      messagingSenderId: "747696032790",
      appId: "1:747696032790:web:4ba68fef5c99c1e7a6f937",
      measurementId: "G-36XHST1B6C"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT_UAgEma4wCy-MsxZbjsx-7B3fcrrOhw',
    appId: '1:747696032790:android:5947a16d0f93e0d0a6f937',
    messagingSenderId: '747696032790',
    projectId: 'dash-cdb16',
    storageBucket: 'dash-cdb16.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_UAgEma4wCy-MsxZbjsx-7B3fcrrOhw',
    appId: '1:747696032790:android:5947a16d0f93e0d0a6f937',
    messagingSenderId: '747696032790',
    projectId: 'dash-cdb16',
    storageBucket: 'dash-cdb16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPcJRkavKKoTIkDNC5MwrUo29Qgt9b_Q',
    appId: '1:747696032790:ios:a736f203d7dc73fea6f937',
    messagingSenderId: '747696032790',
    projectId: 'dash-cdb16',
    storageBucket: 'dash-cdb16.appspot.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPcJRkavKKoTIkDNC5MwrUo29Qgt9b_Q',
    appId: '1:747696032790:ios:da36cf15296d659ca6f937',
    messagingSenderId: '747696032790',
    projectId: 'dash-cdb16',
    storageBucket: 'dash-cdb16.appspot.com',
    iosBundleId: 'com.example.dash.RunnerTests',
  );

}
